FROM nginx:alpine


RUN apk add --no-cache openssl
RUN apk add --no-cache bash
RUN apk add --no-cache openrc

#

# 기본 설정 파일을 지우고, 새로운 파일로 대체합니다.
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

#CMD ./bashForNginx.sh 
RUN nginx -v
CMD ["nginx", "-g", "daemon off;"]